### ISSUE TITLE
Read the Docs Link

### ISSUE THREAD

**Issue by bbengfort** [tusing/Conduit#3]
Hi @tusing - I'm working on a Python package called [Conduit](https://pypi.org/project/conduit/) for power engineering analytics using the [BTrDB database](http://btrdb.io/). I noticed that you have the [conduit.readthedocs.io](https://conduit.readthedocs.io/en/latest/) namespace, though there doesn't appear to be any documentation there. Would you be willing to give up the namespace so that I could host my documentation at that link? I'd really appreciate it if you'd consider it!

**Comment by tusing** [comment]
Done!

**Comment by bbengfort** [comment]
Thank you so much! I really appreciate it! Please let me know if I can return the favor in any way!
